# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import cloudsaveValidatorService_pb2 as cloudsaveValidatorService__pb2


class CloudsaveValidatorServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.BeforeWriteGameRecord = channel.unary_unary(
                '/accelbyte.cloudsave.validator.CloudsaveValidatorService/BeforeWriteGameRecord',
                request_serializer=cloudsaveValidatorService__pb2.GameRecord.SerializeToString,
                response_deserializer=cloudsaveValidatorService__pb2.GameRecordValidationResult.FromString,
                )
        self.AfterReadGameRecord = channel.unary_unary(
                '/accelbyte.cloudsave.validator.CloudsaveValidatorService/AfterReadGameRecord',
                request_serializer=cloudsaveValidatorService__pb2.GameRecord.SerializeToString,
                response_deserializer=cloudsaveValidatorService__pb2.GameRecordValidationResult.FromString,
                )
        self.AfterBulkReadGameRecord = channel.unary_unary(
                '/accelbyte.cloudsave.validator.CloudsaveValidatorService/AfterBulkReadGameRecord',
                request_serializer=cloudsaveValidatorService__pb2.BulkGameRecord.SerializeToString,
                response_deserializer=cloudsaveValidatorService__pb2.BulkGameRecordValidationResult.FromString,
                )
        self.BeforeWritePlayerRecord = channel.unary_unary(
                '/accelbyte.cloudsave.validator.CloudsaveValidatorService/BeforeWritePlayerRecord',
                request_serializer=cloudsaveValidatorService__pb2.PlayerRecord.SerializeToString,
                response_deserializer=cloudsaveValidatorService__pb2.PlayerRecordValidationResult.FromString,
                )
        self.AfterReadPlayerRecord = channel.unary_unary(
                '/accelbyte.cloudsave.validator.CloudsaveValidatorService/AfterReadPlayerRecord',
                request_serializer=cloudsaveValidatorService__pb2.PlayerRecord.SerializeToString,
                response_deserializer=cloudsaveValidatorService__pb2.PlayerRecordValidationResult.FromString,
                )
        self.AfterBulkReadPlayerRecord = channel.unary_unary(
                '/accelbyte.cloudsave.validator.CloudsaveValidatorService/AfterBulkReadPlayerRecord',
                request_serializer=cloudsaveValidatorService__pb2.BulkPlayerRecord.SerializeToString,
                response_deserializer=cloudsaveValidatorService__pb2.BulkPlayerRecordValidationResult.FromString,
                )
        self.BeforeWriteAdminGameRecord = channel.unary_unary(
                '/accelbyte.cloudsave.validator.CloudsaveValidatorService/BeforeWriteAdminGameRecord',
                request_serializer=cloudsaveValidatorService__pb2.AdminGameRecord.SerializeToString,
                response_deserializer=cloudsaveValidatorService__pb2.GameRecordValidationResult.FromString,
                )
        self.BeforeWriteAdminPlayerRecord = channel.unary_unary(
                '/accelbyte.cloudsave.validator.CloudsaveValidatorService/BeforeWriteAdminPlayerRecord',
                request_serializer=cloudsaveValidatorService__pb2.AdminPlayerRecord.SerializeToString,
                response_deserializer=cloudsaveValidatorService__pb2.PlayerRecordValidationResult.FromString,
                )
        self.BeforeWriteGameBinaryRecord = channel.unary_unary(
                '/accelbyte.cloudsave.validator.CloudsaveValidatorService/BeforeWriteGameBinaryRecord',
                request_serializer=cloudsaveValidatorService__pb2.GameBinaryRecord.SerializeToString,
                response_deserializer=cloudsaveValidatorService__pb2.GameRecordValidationResult.FromString,
                )
        self.AfterReadGameBinaryRecord = channel.unary_unary(
                '/accelbyte.cloudsave.validator.CloudsaveValidatorService/AfterReadGameBinaryRecord',
                request_serializer=cloudsaveValidatorService__pb2.GameBinaryRecord.SerializeToString,
                response_deserializer=cloudsaveValidatorService__pb2.GameRecordValidationResult.FromString,
                )
        self.AfterBulkReadGameBinaryRecord = channel.unary_unary(
                '/accelbyte.cloudsave.validator.CloudsaveValidatorService/AfterBulkReadGameBinaryRecord',
                request_serializer=cloudsaveValidatorService__pb2.BulkGameBinaryRecord.SerializeToString,
                response_deserializer=cloudsaveValidatorService__pb2.BulkGameRecordValidationResult.FromString,
                )
        self.BeforeWritePlayerBinaryRecord = channel.unary_unary(
                '/accelbyte.cloudsave.validator.CloudsaveValidatorService/BeforeWritePlayerBinaryRecord',
                request_serializer=cloudsaveValidatorService__pb2.PlayerBinaryRecord.SerializeToString,
                response_deserializer=cloudsaveValidatorService__pb2.PlayerRecordValidationResult.FromString,
                )
        self.AfterReadPlayerBinaryRecord = channel.unary_unary(
                '/accelbyte.cloudsave.validator.CloudsaveValidatorService/AfterReadPlayerBinaryRecord',
                request_serializer=cloudsaveValidatorService__pb2.PlayerBinaryRecord.SerializeToString,
                response_deserializer=cloudsaveValidatorService__pb2.PlayerRecordValidationResult.FromString,
                )
        self.AfterBulkReadPlayerBinaryRecord = channel.unary_unary(
                '/accelbyte.cloudsave.validator.CloudsaveValidatorService/AfterBulkReadPlayerBinaryRecord',
                request_serializer=cloudsaveValidatorService__pb2.BulkPlayerBinaryRecord.SerializeToString,
                response_deserializer=cloudsaveValidatorService__pb2.BulkPlayerRecordValidationResult.FromString,
                )


class CloudsaveValidatorServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def BeforeWriteGameRecord(self, request, context):
        """game record
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AfterReadGameRecord(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AfterBulkReadGameRecord(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BeforeWritePlayerRecord(self, request, context):
        """player record
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AfterReadPlayerRecord(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AfterBulkReadPlayerRecord(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BeforeWriteAdminGameRecord(self, request, context):
        """admin game record
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BeforeWriteAdminPlayerRecord(self, request, context):
        """admin player record
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BeforeWriteGameBinaryRecord(self, request, context):
        """game binary record
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AfterReadGameBinaryRecord(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AfterBulkReadGameBinaryRecord(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BeforeWritePlayerBinaryRecord(self, request, context):
        """player binary record
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AfterReadPlayerBinaryRecord(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AfterBulkReadPlayerBinaryRecord(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CloudsaveValidatorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'BeforeWriteGameRecord': grpc.unary_unary_rpc_method_handler(
                    servicer.BeforeWriteGameRecord,
                    request_deserializer=cloudsaveValidatorService__pb2.GameRecord.FromString,
                    response_serializer=cloudsaveValidatorService__pb2.GameRecordValidationResult.SerializeToString,
            ),
            'AfterReadGameRecord': grpc.unary_unary_rpc_method_handler(
                    servicer.AfterReadGameRecord,
                    request_deserializer=cloudsaveValidatorService__pb2.GameRecord.FromString,
                    response_serializer=cloudsaveValidatorService__pb2.GameRecordValidationResult.SerializeToString,
            ),
            'AfterBulkReadGameRecord': grpc.unary_unary_rpc_method_handler(
                    servicer.AfterBulkReadGameRecord,
                    request_deserializer=cloudsaveValidatorService__pb2.BulkGameRecord.FromString,
                    response_serializer=cloudsaveValidatorService__pb2.BulkGameRecordValidationResult.SerializeToString,
            ),
            'BeforeWritePlayerRecord': grpc.unary_unary_rpc_method_handler(
                    servicer.BeforeWritePlayerRecord,
                    request_deserializer=cloudsaveValidatorService__pb2.PlayerRecord.FromString,
                    response_serializer=cloudsaveValidatorService__pb2.PlayerRecordValidationResult.SerializeToString,
            ),
            'AfterReadPlayerRecord': grpc.unary_unary_rpc_method_handler(
                    servicer.AfterReadPlayerRecord,
                    request_deserializer=cloudsaveValidatorService__pb2.PlayerRecord.FromString,
                    response_serializer=cloudsaveValidatorService__pb2.PlayerRecordValidationResult.SerializeToString,
            ),
            'AfterBulkReadPlayerRecord': grpc.unary_unary_rpc_method_handler(
                    servicer.AfterBulkReadPlayerRecord,
                    request_deserializer=cloudsaveValidatorService__pb2.BulkPlayerRecord.FromString,
                    response_serializer=cloudsaveValidatorService__pb2.BulkPlayerRecordValidationResult.SerializeToString,
            ),
            'BeforeWriteAdminGameRecord': grpc.unary_unary_rpc_method_handler(
                    servicer.BeforeWriteAdminGameRecord,
                    request_deserializer=cloudsaveValidatorService__pb2.AdminGameRecord.FromString,
                    response_serializer=cloudsaveValidatorService__pb2.GameRecordValidationResult.SerializeToString,
            ),
            'BeforeWriteAdminPlayerRecord': grpc.unary_unary_rpc_method_handler(
                    servicer.BeforeWriteAdminPlayerRecord,
                    request_deserializer=cloudsaveValidatorService__pb2.AdminPlayerRecord.FromString,
                    response_serializer=cloudsaveValidatorService__pb2.PlayerRecordValidationResult.SerializeToString,
            ),
            'BeforeWriteGameBinaryRecord': grpc.unary_unary_rpc_method_handler(
                    servicer.BeforeWriteGameBinaryRecord,
                    request_deserializer=cloudsaveValidatorService__pb2.GameBinaryRecord.FromString,
                    response_serializer=cloudsaveValidatorService__pb2.GameRecordValidationResult.SerializeToString,
            ),
            'AfterReadGameBinaryRecord': grpc.unary_unary_rpc_method_handler(
                    servicer.AfterReadGameBinaryRecord,
                    request_deserializer=cloudsaveValidatorService__pb2.GameBinaryRecord.FromString,
                    response_serializer=cloudsaveValidatorService__pb2.GameRecordValidationResult.SerializeToString,
            ),
            'AfterBulkReadGameBinaryRecord': grpc.unary_unary_rpc_method_handler(
                    servicer.AfterBulkReadGameBinaryRecord,
                    request_deserializer=cloudsaveValidatorService__pb2.BulkGameBinaryRecord.FromString,
                    response_serializer=cloudsaveValidatorService__pb2.BulkGameRecordValidationResult.SerializeToString,
            ),
            'BeforeWritePlayerBinaryRecord': grpc.unary_unary_rpc_method_handler(
                    servicer.BeforeWritePlayerBinaryRecord,
                    request_deserializer=cloudsaveValidatorService__pb2.PlayerBinaryRecord.FromString,
                    response_serializer=cloudsaveValidatorService__pb2.PlayerRecordValidationResult.SerializeToString,
            ),
            'AfterReadPlayerBinaryRecord': grpc.unary_unary_rpc_method_handler(
                    servicer.AfterReadPlayerBinaryRecord,
                    request_deserializer=cloudsaveValidatorService__pb2.PlayerBinaryRecord.FromString,
                    response_serializer=cloudsaveValidatorService__pb2.PlayerRecordValidationResult.SerializeToString,
            ),
            'AfterBulkReadPlayerBinaryRecord': grpc.unary_unary_rpc_method_handler(
                    servicer.AfterBulkReadPlayerBinaryRecord,
                    request_deserializer=cloudsaveValidatorService__pb2.BulkPlayerBinaryRecord.FromString,
                    response_serializer=cloudsaveValidatorService__pb2.BulkPlayerRecordValidationResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'accelbyte.cloudsave.validator.CloudsaveValidatorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CloudsaveValidatorService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def BeforeWriteGameRecord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/accelbyte.cloudsave.validator.CloudsaveValidatorService/BeforeWriteGameRecord',
            cloudsaveValidatorService__pb2.GameRecord.SerializeToString,
            cloudsaveValidatorService__pb2.GameRecordValidationResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AfterReadGameRecord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/accelbyte.cloudsave.validator.CloudsaveValidatorService/AfterReadGameRecord',
            cloudsaveValidatorService__pb2.GameRecord.SerializeToString,
            cloudsaveValidatorService__pb2.GameRecordValidationResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AfterBulkReadGameRecord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/accelbyte.cloudsave.validator.CloudsaveValidatorService/AfterBulkReadGameRecord',
            cloudsaveValidatorService__pb2.BulkGameRecord.SerializeToString,
            cloudsaveValidatorService__pb2.BulkGameRecordValidationResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BeforeWritePlayerRecord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/accelbyte.cloudsave.validator.CloudsaveValidatorService/BeforeWritePlayerRecord',
            cloudsaveValidatorService__pb2.PlayerRecord.SerializeToString,
            cloudsaveValidatorService__pb2.PlayerRecordValidationResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AfterReadPlayerRecord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/accelbyte.cloudsave.validator.CloudsaveValidatorService/AfterReadPlayerRecord',
            cloudsaveValidatorService__pb2.PlayerRecord.SerializeToString,
            cloudsaveValidatorService__pb2.PlayerRecordValidationResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AfterBulkReadPlayerRecord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/accelbyte.cloudsave.validator.CloudsaveValidatorService/AfterBulkReadPlayerRecord',
            cloudsaveValidatorService__pb2.BulkPlayerRecord.SerializeToString,
            cloudsaveValidatorService__pb2.BulkPlayerRecordValidationResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BeforeWriteAdminGameRecord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/accelbyte.cloudsave.validator.CloudsaveValidatorService/BeforeWriteAdminGameRecord',
            cloudsaveValidatorService__pb2.AdminGameRecord.SerializeToString,
            cloudsaveValidatorService__pb2.GameRecordValidationResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BeforeWriteAdminPlayerRecord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/accelbyte.cloudsave.validator.CloudsaveValidatorService/BeforeWriteAdminPlayerRecord',
            cloudsaveValidatorService__pb2.AdminPlayerRecord.SerializeToString,
            cloudsaveValidatorService__pb2.PlayerRecordValidationResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BeforeWriteGameBinaryRecord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/accelbyte.cloudsave.validator.CloudsaveValidatorService/BeforeWriteGameBinaryRecord',
            cloudsaveValidatorService__pb2.GameBinaryRecord.SerializeToString,
            cloudsaveValidatorService__pb2.GameRecordValidationResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AfterReadGameBinaryRecord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/accelbyte.cloudsave.validator.CloudsaveValidatorService/AfterReadGameBinaryRecord',
            cloudsaveValidatorService__pb2.GameBinaryRecord.SerializeToString,
            cloudsaveValidatorService__pb2.GameRecordValidationResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AfterBulkReadGameBinaryRecord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/accelbyte.cloudsave.validator.CloudsaveValidatorService/AfterBulkReadGameBinaryRecord',
            cloudsaveValidatorService__pb2.BulkGameBinaryRecord.SerializeToString,
            cloudsaveValidatorService__pb2.BulkGameRecordValidationResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BeforeWritePlayerBinaryRecord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/accelbyte.cloudsave.validator.CloudsaveValidatorService/BeforeWritePlayerBinaryRecord',
            cloudsaveValidatorService__pb2.PlayerBinaryRecord.SerializeToString,
            cloudsaveValidatorService__pb2.PlayerRecordValidationResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AfterReadPlayerBinaryRecord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/accelbyte.cloudsave.validator.CloudsaveValidatorService/AfterReadPlayerBinaryRecord',
            cloudsaveValidatorService__pb2.PlayerBinaryRecord.SerializeToString,
            cloudsaveValidatorService__pb2.PlayerRecordValidationResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AfterBulkReadPlayerBinaryRecord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/accelbyte.cloudsave.validator.CloudsaveValidatorService/AfterBulkReadPlayerBinaryRecord',
            cloudsaveValidatorService__pb2.BulkPlayerBinaryRecord.SerializeToString,
            cloudsaveValidatorService__pb2.BulkPlayerRecordValidationResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
